apiVersion: v1
kind: Service
metadata:
  name: bff-frontend-service
spec:
  selector:
    app: bff-y-frontend-pod  # Asegúrate de que esto coincida con el label de tu Pod.
  ports:
    - name: bff-port
      port: 3000              # Puerto interno del servicio
      targetPort: 3000      # Puerto del contenedor bff-container
      nodePort: 30001       # Puerto expuesto en tu máquina local para bff
    - name: frontend-port
      port: 5173            # Puerto interno del servicio
      targetPort: 5173      # Puerto del contenedor frontend-container
      nodePort: 30002       # Puerto expuesto en tu máquina local para frontend
  type: NodePort
